# language: English
### main program
EXIT = "Exit"
UPPER_FOLDER = "Up"
HISTORY_OP = "History of opened folders"
FOLDER_NOT_EXIST = "\nThe selected folder doesn't exist anymore."
MISSED_PATH = "\nMissed path:\n"

### iconview module
# name of the info page in notebook2
INFO_NAME = 'Info'
I_SHOW_HID = "Show hidden items"
I_INV_SEL = "Invert the selection"
INAME = "Name "
IPATH = "Path "
ITYPE = "Type "
ISIZE = "Size "
ISIZE2 = "Free space "
IITEMS = "Items "
ISELITM = "Selected Items "
ITMSIZE = "Items Size "
IHIDDEN = "Hiddens "
IOPENNT = "Open in a new tab"
INEWFOLDER = "New Folder"
INEWFILE = "New File"
IMAKELINK = "Make link"
ILINKTO = "Link to "
IPASTE = "Paste"
INEWFOLDER2 = "New Folder"
ICHOOSENAMEFOLD = "Choose a name for the folder"
ICHOOSENAMEFILE = "Choose a name for the file"
IOPENWITH = "Open With"
IOTHERAPP = "Other Applications..."
ICUT = "Cut"
ICOPY = "Copy"
IRENAME = "Rename..."
IMOVETOTRASH = "Move to Trash"
IDELETE = "Delete"
IENTERNNAMEFOR = "Enter a new name for"
INAMEBUSY = "\nName already taken"
IUNKNOWN = "unknown"
IFAILED = "Failed"
IENTERNEWNAME = "Enter a new name"
IERROR = "Error"
IERROR2 = "\nError while opening the file:"
IRECBIN1 = "Recycle Bin"
IRECBIN2 = "\nCannot move items to Recycle Bin."
IERR_ACCESS_FOLDER = "\nCreating files and folders is not allowed.\nNo writing rights."
IDATA = "Data"
IDATE = "Date"
IPERMISSIONS = "Permissions "
ICREATED = "Created "
IMODIFIED = "Modified "
ILASTACCESS = "Last access "
IEXECFILE = "\n  Would you like to exec or open this file?  \n"
IBUTTONC = "Cancel"
IBUTTONE = "Exec"
IBUTTONO = "Open"
INFREESPACE = "\nNot enough free space."

### items_copy module
ICCANCEL = "Cancel"
ICCLOSE = "Close"
IISCPY = "Copying..."
IISMOV = "Moving..."
IISLNK = "Linking..."
ICOPTERM = "Operation terminated"
ICOPSTD = "Operation started"
ICOPINTD = "Operation cancelled"
ICOERRITEM = "Operation cancelled\nError with the file:"
ICOERRDISC = "Operation cancelled\nError with the disc\nwhile copying:"

### trash module
TLABEL = "Trash"
TRESTORE = "Restore"
TDELETE = "Delete"
TNAME = "Name "
TPATH = "Path "
TTYPE = "Type "
TITEMS = "Items "
TSIZE = "Size "
TDATE = "Date "
TSELITEM = "Selected Items: "
TEMPTY_RBIN = "Empty Recycle Bin"
TMESS_EMPTY = "\nThe recycle bin will be empty. Continue?"
TLINK = "Is link"
